"""create career dna schema

Revision ID: 6d309ce6ef33
Revises: 0001_create_users_table
Create Date: 2026-08-04 11:08:45.575938

Note on hand-editing (Sprint 2): autogenerate produced the upgrade()/
downgrade() bodies below unedited, EXCEPT for one addition at the end of
downgrade() -- see the comment there. Verified with a real embedded-
PostgreSQL round-trip (upgrade -> downgrade -> upgrade) during this
session; the round-trip failed on the first attempt with exactly the bug
that addition fixes (see docs/CAREER_DNA_MIGRATION_GUIDE.md).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d309ce6ef33'
down_revision: Union[str, None] = '0001_create_users_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every custom PostgreSQL enum type this migration's tables create.
# Alembic's autogenerate emits CREATE TYPE implicitly (via each column's
# sa.Enum(...)) but does NOT emit matching DROP TYPE statements in
# downgrade() -- a known autogenerate limitation, confirmed here by a
# real downgrade-then-upgrade round-trip against embedded PostgreSQL
# failing with "type already exists" on the second upgrade. This list
# is used once, at the end of downgrade(), to clean them up explicitly.
_ENUM_TYPE_NAMES = [
    "attribution_source", "proficiency_level", "employment_type",
    "seniority_level", "skill_type", "technology_category", "degree_level",
    "publication_type", "portfolio_entity_type", "evidence_type",
    "evidence_subject_type", "career_goal_type", "goal_priority",
    "goal_status", "location_preference_type", "company_size_preference",
    "salary_period", "career_stage", "career_stage_source",
    "profile_visibility", "employer_size_range",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_name'), 'competency', ['name'], unique=False)
    op.create_index(op.f('ix_competency_normalized_name'), 'competency', ['normalized_name'], unique=True)
    op.create_table('industry',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_industry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_industry_id'], ['industry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_name'), 'industry', ['name'], unique=True)
    op.create_table('job_family',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_job_family_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_family_id'], ['job_family.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_family_name'), 'job_family', ['name'], unique=True)
    op.create_table('skill',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=False),
    sa.Column('skill_type', sa.Enum('soft', 'domain', 'technical', name='skill_type'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=False)
    op.create_index(op.f('ix_skill_normalized_name'), 'skill', ['normalized_name'], unique=True)
    op.create_table('technology',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('language', 'framework', 'tool', 'platform', 'database', 'other', name='technology_category'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_name'), 'technology', ['name'], unique=False)
    op.create_index(op.f('ix_technology_normalized_name'), 'technology', ['normalized_name'], unique=True)
    op.create_table('competency_skill',
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('competency_id', 'skill_id')
    )
    op.create_table('employer',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('size_range', sa.Enum('1-10', '11-50', '51-200', '201-1000', '1001-5000', '5001+', name='employer_size_range'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_normalized_name'), 'employer', ['normalized_name'], unique=True)
    op.create_table('occupation',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('standard_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('job_family_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_family_id'], ['job_family.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupation_name'), 'occupation', ['name'], unique=False)
    op.create_table('person',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('career_goal',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('role', 'industry', 'skill_development', 'salary', 'other', name='career_goal_type'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='goal_priority'), server_default='medium', nullable=False),
    sa.Column('status', sa.Enum('active', 'achieved', 'abandoned', name='goal_status'), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_goal_person_id'), 'career_goal', ['person_id'], unique=False)
    op.create_table('career_profile',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('career_stage', sa.Enum('entry', 'mid', 'senior', 'lead', 'executive', name='career_stage'), nullable=True),
    sa.Column('career_stage_source', sa.Enum('self_reported', 'derived', name='career_stage_source'), server_default='self_reported', nullable=False),
    sa.Column('total_experience_months', sa.Integer(), nullable=True),
    sa.Column('primary_industry_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'platform', name='profile_visibility'), server_default='private', nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_industry_id'], ['industry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('certification',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verification_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_person_id'), 'certification', ['person_id'], unique=False)
    op.create_table('education',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('degree_level', sa.Enum('high_school', 'associate', 'bachelor', 'master', 'doctorate', 'professional', 'other', name='degree_level'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_person_id'), 'education', ['person_id'], unique=False)
    op.create_table('evidence',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('url', 'document', 'testimonial', 'metric', 'media', name='evidence_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_person_id'), 'evidence', ['person_id'], unique=False)
    op.create_table('location_preference',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('location_text', sa.String(length=255), nullable=False),
    sa.Column('preference_type', sa.Enum('remote', 'hybrid', 'onsite', name='location_preference_type'), nullable=False),
    sa.Column('willing_to_relocate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_commute_minutes', sa.Integer(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_preference_person_id'), 'location_preference', ['person_id'], unique=False)
    op.create_table('person_competency',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level'), nullable=False),
    sa.Column('attribution_source', sa.Enum('self_reported', 'inferred', 'verified', name='attribution_source'), server_default='self_reported', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'competency_id', name='ux_person_competency')
    )
    op.create_index(op.f('ix_person_competency_person_id'), 'person_competency', ['person_id'], unique=False)
    op.create_table('person_technology',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level'), nullable=False),
    sa.Column('years_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('attribution_source', sa.Enum('self_reported', 'inferred', 'verified', name='attribution_source'), server_default='self_reported', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'technology_id', name='ux_person_technology')
    )
    op.create_index(op.f('ix_person_technology_person_id'), 'person_technology', ['person_id'], unique=False)
    op.create_table('portfolio_item',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('linked_entity_type', sa.Enum('project', 'publication', 'achievement', name='portfolio_entity_type'), nullable=False),
    sa.Column('linked_entity_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_entity_type', 'linked_entity_id', name='ux_portfolio_item_linked_entity')
    )
    op.create_index(op.f('ix_portfolio_item_person_id'), 'portfolio_item', ['person_id'], unique=False)
    op.create_table('publication',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publication_type', sa.Enum('article', 'paper', 'patent', 'talk', 'book', 'other', name='publication_type'), nullable=False),
    sa.Column('publisher_or_venue', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('co_authors', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_person_id'), 'publication', ['person_id'], unique=False)
    op.create_table('reference',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('referee_name', sa.String(length=255), nullable=False),
    sa.Column('referee_title', sa.String(length=255), nullable=True),
    sa.Column('referee_employer', sa.String(length=255), nullable=True),
    sa.Column('relationship_description', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('can_contact', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('testimonial_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_person_id'), 'reference', ['person_id'], unique=False)
    op.create_table('role',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=False),
    sa.Column('seniority_level', sa.Enum('intern', 'junior', 'mid', 'senior', 'lead', 'principal', 'executive', name='seniority_level'), nullable=True),
    sa.Column('occupation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_normalized_title'), 'role', ['normalized_title'], unique=True)
    op.create_index(op.f('ix_role_title'), 'role', ['title'], unique=False)
    op.create_table('salary_preference',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('period', sa.Enum('annual', 'monthly', 'hourly', 'daily_rate', name='salary_period'), nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('work_preference',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('preferred_employment_types', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('company_size_preference', sa.Enum('startup', 'scaleup', 'midsize', 'enterprise', 'no_preference', name='company_size_preference'), server_default='no_preference', nullable=False),
    sa.Column('culture_values', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('career_profile_snapshot',
    sa.Column('career_profile_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('role_title_raw', sa.String(length=255), nullable=False),
    sa.Column('previous_employment_id', sa.UUID(), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'freelance', 'internship', name='employment_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_employment_id'], ['employment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_person_id'), 'employment', ['person_id'], unique=False)
    op.create_index('ux_employment_one_primary_current_per_person', 'employment', ['person_id'], unique=True, postgresql_where=sa.text("is_current AND employment_type IN ('full_time','part_time')"), sqlite_where=sa.text("is_current AND employment_type IN ('full_time','part_time')"))
    op.create_table('evidence_link',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Enum('person_skill', 'person_competency', 'person_technology', 'certification', 'education', 'project', 'achievement', 'publication', 'reference', name='evidence_subject_type'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'subject_type', 'subject_id', name='ux_evidence_link_subject')
    )
    op.create_index(op.f('ix_evidence_link_evidence_id'), 'evidence_link', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_link_subject_id'), 'evidence_link', ['subject_id'], unique=False)
    op.create_table('person_skill',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level'), nullable=False),
    sa.Column('years_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('attribution_source', sa.Enum('self_reported', 'inferred', 'verified', name='attribution_source'), server_default='self_reported', nullable=False),
    sa.Column('employment_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'skill_id', name='ux_person_skill')
    )
    op.create_index(op.f('ix_person_skill_person_id'), 'person_skill', ['person_id'], unique=False)
    op.create_table('project',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('employment_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_in_project', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_person_id'), 'project', ['person_id'], unique=False)
    op.create_table('achievement',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('employment_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('achieved_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_person_id'), 'achievement', ['person_id'], unique=False)
    op.create_table('project_skill',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    op.create_table('project_technology',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'technology_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_technology')
    op.drop_table('project_skill')
    op.drop_index(op.f('ix_achievement_person_id'), table_name='achievement')
    op.drop_table('achievement')
    op.drop_index(op.f('ix_project_person_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_person_skill_person_id'), table_name='person_skill')
    op.drop_table('person_skill')
    op.drop_index(op.f('ix_evidence_link_subject_id'), table_name='evidence_link')
    op.drop_index(op.f('ix_evidence_link_evidence_id'), table_name='evidence_link')
    op.drop_table('evidence_link')
    op.drop_index('ux_employment_one_primary_current_per_person', table_name='employment', postgresql_where=sa.text("is_current AND employment_type IN ('full_time','part_time')"), sqlite_where=sa.text("is_current AND employment_type IN ('full_time','part_time')"))
    op.drop_index(op.f('ix_employment_person_id'), table_name='employment')
    op.drop_table('employment')
    op.drop_table('career_profile_snapshot')
    op.drop_table('work_preference')
    op.drop_table('salary_preference')
    op.drop_index(op.f('ix_role_title'), table_name='role')
    op.drop_index(op.f('ix_role_normalized_title'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_reference_person_id'), table_name='reference')
    op.drop_table('reference')
    op.drop_index(op.f('ix_publication_person_id'), table_name='publication')
    op.drop_table('publication')
    op.drop_index(op.f('ix_portfolio_item_person_id'), table_name='portfolio_item')
    op.drop_table('portfolio_item')
    op.drop_index(op.f('ix_person_technology_person_id'), table_name='person_technology')
    op.drop_table('person_technology')
    op.drop_index(op.f('ix_person_competency_person_id'), table_name='person_competency')
    op.drop_table('person_competency')
    op.drop_index(op.f('ix_location_preference_person_id'), table_name='location_preference')
    op.drop_table('location_preference')
    op.drop_index(op.f('ix_evidence_person_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_education_person_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_certification_person_id'), table_name='certification')
    op.drop_table('certification')
    op.drop_table('career_profile')
    op.drop_index(op.f('ix_career_goal_person_id'), table_name='career_goal')
    op.drop_table('career_goal')
    op.drop_table('person')
    op.drop_index(op.f('ix_occupation_name'), table_name='occupation')
    op.drop_table('occupation')
    op.drop_index(op.f('ix_employer_normalized_name'), table_name='employer')
    op.drop_table('employer')
    op.drop_table('competency_skill')
    op.drop_index(op.f('ix_technology_normalized_name'), table_name='technology')
    op.drop_index(op.f('ix_technology_name'), table_name='technology')
    op.drop_table('technology')
    op.drop_index(op.f('ix_skill_normalized_name'), table_name='skill')
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_job_family_name'), table_name='job_family')
    op.drop_table('job_family')
    op.drop_index(op.f('ix_industry_name'), table_name='industry')
    op.drop_table('industry')
    op.drop_index(op.f('ix_competency_normalized_name'), table_name='competency')
    op.drop_index(op.f('ix_competency_name'), table_name='competency')
    op.drop_table('competency')
    # ### end Alembic commands ###

    # Hand-added (not autogenerated -- see the module docstring and
    # _ENUM_TYPE_NAMES above): drop every custom enum type this migration
    # created. PostgreSQL-only -- on SQLite these columns are plain
    # VARCHAR with a CHECK constraint, dropped automatically with their
    # table, and DROP TYPE has no SQLite equivalent to run.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for type_name in _ENUM_TYPE_NAMES:
            op.execute(f"DROP TYPE IF EXISTS {type_name}")
