"""extend attribution_source enum for document intelligence

Revision ID: 7f4a1b2c9d3e
Revises: 6d309ce6ef33
Create Date: 2026-08-05 00:00:00.000000

Adds two new AttributionSource values (ai_extracted, imported) per
ADR 0005 Decision 3 / ADR 0006 -- see app/models/enums.py's
AttributionSource docstring for why this extends the existing enum
rather than renaming its existing members.

Hand-written, not autogenerated: Alembic's autogenerate does not detect
new enum member additions to an existing PostgreSQL enum type at all
(it only detects new/dropped columns and tables) -- this must be
written by hand every time an existing enum type gains a value.

PostgreSQL-only operation: `ALTER TYPE ... ADD VALUE` cannot run inside
a transaction block in PostgreSQL (it was only permitted since PG 12,
and even then only outside an explicit transaction), so this uses
Alembic's `autocommit_block()`. On SQLite, this enum is a plain VARCHAR
with a CHECK constraint baked in at table-creation time from the
current Python enum definition (see the career_dna migration's own
docstring on this same distinction) -- there is nothing to ALTER on
SQLite, and this project's test suite creates schema via
`Base.metadata.create_all()` directly rather than by running Alembic
migrations, so SQLite never executes this migration at all in practice.
This upgrade() is therefore a no-op, not an error, when run against
SQLite, for defensiveness only.

NOTE: not yet verified against a live PostgreSQL instance in this
session (no PostgreSQL available in this sandbox) -- this must be run
via `alembic upgrade head` against real PostgreSQL and confirmed before
Stage 1 is considered done, per this project's established verification
discipline. See docs/SPRINT-3-STAGE1-TEST-STRATEGY.md.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f4a1b2c9d3e'
down_revision: Union[str, None] = '6d309ce6ef33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_NEW_VALUES = ["ai_extracted", "imported"]


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    with op.get_context().autocommit_block():
        for value in _NEW_VALUES:
            op.execute(f"ALTER TYPE attribution_source ADD VALUE IF NOT EXISTS '{value}'")


def downgrade() -> None:
    # PostgreSQL does not support removing a value from an existing enum
    # type (ALTER TYPE ... DROP VALUE does not exist). The only way to
    # truly reverse this is to recreate the type without the new values
    # and remap every column using it, which is destructive far beyond
    # the scope of a routine downgrade and would risk data loss on any
    # row already using ai_extracted/imported. Consistent with this
    # project's Truth First principle: rather than silently no-op
    # downgrade() (implying success) or attempt a lossy type-rebuild
    # migration nobody asked for, this raises explicitly so a downgrade
    # attempt fails loudly instead of misleadingly.
    raise NotImplementedError(
        "Cannot cleanly downgrade an added PostgreSQL enum value. "
        "If you need to revert this, that requires a manual, reviewed "
        "data migration -- not an automatic 'alembic downgrade'."
    )
